version: "3"

services:
  db:
    container_name: sample_db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build: ./api
    volumes:
      - ./api:/myapp
    depends_on:
      - db

  front:
    container_name: sample_front
    build: front/
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 8080:3000
    depends_on:
      - api
